// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyA4cMt7U4M7zk1MJGJKqrLvVD8XIMa_k',
    appId: '1:285477666870:web:74bc35b031637beba51897',
    messagingSenderId: '285477666870',
    projectId: 'campo-minado-flutter',
    authDomain: 'campo-minado-flutter.firebaseapp.com',
    storageBucket: 'campo-minado-flutter.firebasestorage.app',
    measurementId: 'G-W4NQPWTCCB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe_fRYL4g7TU2xP_SN4_kC7j54B4liQI4',
    appId: '1:285477666870:android:e166d0d29c58fb00a51897',
    messagingSenderId: '285477666870',
    projectId: 'campo-minado-flutter',
    storageBucket: 'campo-minado-flutter.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNu1TdYTRh727SOMGIC3YrYSwvQi2kAnE',
    appId: '1:285477666870:ios:6762dba1c1d1c336a51897',
    messagingSenderId: '285477666870',
    projectId: 'campo-minado-flutter',
    storageBucket: 'campo-minado-flutter.firebasestorage.app',
    iosBundleId: 'com.example.appCampo',
  );
}
